@startuml
!include ../style.puml

Actor User as user USER_COLOR
Participant ":Ui" as ui UI_COLOR
Participant ":Parser" as parser LOGIC_COLOR_T1
Participant ":CommandRunner" as runner LOGIC_COLOR
Participant ":SkuCommandHandler" as skuHandler LOGIC_COLOR
Participant ":TaskCommandHandler" as taskHandler LOGIC_COLOR
Participant ":ViewCommandHandler" as viewHandler LOGIC_COLOR

user -> ui ++ : "deletesku n/PALLET-A"
ui -> parser ++ : parse("deletesku n/PALLET-A")
return cmd : ParsedCommand

ui -> runner ++ : run(cmd)
runner -> runner ++ : cmd.getCommandWord()
return "deletesku"

alt commandWord == "addsku" / "deletesku" / "editsku"
  runner -> skuHandler ++ : handleDeleteSku(cmd)
  return
else commandWord == "addskutask" / "edittask" / "deletetask" / "marktask" / "unmarktask"
  runner -> taskHandler ++ : handleXxx(cmd)
  return
else commandWord == "listtasks" / "find"
  runner -> viewHandler ++ : handleXxx(cmd)
  return
else commandWord == "bye" / "exit"
  runner -> runner : Storage.saveState(skuList)
  runner -> ui : printGoodbye()
  runner -> runner : isRunning = false
end

return
return
@enduml
