@startuml
!include ../style.puml

Actor User as user USER_COLOR
Participant ":Ui" as ui UI_COLOR
Participant ":Parser" as parser LOGIC_COLOR_T1
Participant ":ParsedCommand" as cmd LOGIC_COLOR
Participant ":CommandRunner" as runner LOGIC_COLOR

user -> ui ++ : "listtasks p/HIGH"
ui -> parser ++ : parse("listtasks p/HIGH")
parser -> cmd ** : create("listtasks", {p: "HIGH"})
activate cmd LOGIC_COLOR
return cmd : ParsedCommand

ui -> runner ++ : run(cmd)
runner -> cmd ++ : getCommandWord()
return "listtasks"
runner -> cmd ++ : getArg("p")
return "HIGH"
return
return
@enduml
