@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam classAttributeIconSize 0

class SkuCommandHandler LOGIC_COLOR {
  + handleAddSku(cmd: ParsedCommand): void
  + handleEditSku(cmd: ParsedCommand): void
  + handleDeleteSku(cmd: ParsedCommand): void
}

class SKUList MODEL_COLOR {
  + addSKU(skuID: String, location: Location): void
  + deleteSKU(skuID: String): void
  + findByID(skuID: String): SKU
}

class SKU MODEL_COLOR_T1 {
  - skuID: String
  - skuLocation: Location
  + setLocation(location: Location): void
}

class SKUTaskList MODEL_COLOR_T2 {
}

SkuCommandHandler -down-> "1" SKUList : skuList
SKUList -down-> "*" SKU : skuList
SKU -down-> "1" SKUTaskList : skuTaskList
@enduml
