@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam classAttributeIconSize 0

class TaskCommandHandler LOGIC_COLOR {
  + handleAddSkuTask(cmd: ParsedCommand): void
  + handleEditTask(cmd: ParsedCommand): void
  + handleDeleteTask(cmd: ParsedCommand): void
  + handleMarkTask(cmd: ParsedCommand): void
  + handleUnmarkTask(cmd: ParsedCommand): void
}

class SKUList MODEL_COLOR {
  + findByID(skuID: String): SKU
}

class SKU MODEL_COLOR_T1 {
  - skuID: String
  + getSKUTaskList(): SKUTaskList
}

class SKUTaskList MODEL_COLOR_T2 {
  + addSKUTask(skuID: String, priority: Priority, dueDate: String, desc: String): void
  + editSKUTask(index: int, date: String, priority: Priority, desc: String): void
  + deleteSKUTaskByIndex(index: int): void
  + markTask(index: int): void
  + unmarkTask(index: int): void
  + getSize(): int
}

TaskCommandHandler -down-> "1" SKUList : skuList
SKUList -down-> "*" SKU : skuList
SKU -down-> "1" SKUTaskList : skuTaskList
@enduml
