@startuml
!include ../style.puml

Actor User as user USER_COLOR
Participant ":Ui" as ui UI_COLOR
Participant ":Parser" as parser LOGIC_COLOR_T1
Participant ":CommandRunner" as runner LOGIC_COLOR
Participant ":ViewCommandHandler" as handler LOGIC_COLOR
Participant ":SKUList" as skuList MODEL_COLOR
Participant ":SKU" as sku MODEL_COLOR_T1

user -> ui ++ : "find n/PALLET-A t/Check"
ui -> parser ++ : parse("find n/PALLET-A t/Check")
return cmd : ParsedCommand

ui -> runner ++ : run(cmd)
runner -> handler ++ : handleFind(cmd)

handler -> handler ++ : validateFindArgs("PALLET-A", "Check", null)
handler -> skuList ++ : findByID("PALLET-A")
return sku
return

handler -> ui : printSearchHeader()

handler -> handler ++ : searchTasks("PALLET-A", "Check", -1)
handler -> skuList ++ : getSKUList()
return List<SKU>
handler -> sku ++ : getSKUTaskList()
return taskList
return results

handler -> ui : printSearchFooter(results)

return
return
return
@enduml
